### ISSUE TITLE
Infinite loop in PineNode.js

### ISSUE THREAD

**Issue by adelq** [Zhong-Lab-UCSD/Genomic-Interactive-Visualization-Engine#37]
When loading a custom genome with some of bigWig tracks, the initial load works, but subsequently the page becomes unresponsive. Upon further investigation, it seems that it is due to an infinite loop in `PineNode.js`, primarily in `give.PineNode.prototype._addLeafRecords`. I'm having a hard time debugging since it goes into an infinite loop, but one atypical feature that may not be desirable is `currIndex` is `-1`, which may be screwing things up. I'm not sure how it got into this state, would be glad to dig further into the problem with any pointers you have.

**Comment by adelq** [comment]
After lots of trial and error, I have narrowed this down to a single bigwig track that GIVE has trouble with. All other bigwig tracks I have tried work fine, and the "problematic" bigwig works fine in IGV but not UCSC. The initial rendering works fine, but nearly immediately afterwards the interface locks up. All the bigwig tracks were made the same way (bam → bed → bigWig), so I'm not sure what this issue is due to.

**Comment by caoxiaoyi03** [comment]
Could you please share the problematic bigWig file? Thanks.

**Comment by adelq** [comment]
Sure, I've sent it over to your email (x9cao).

**Comment by adelq** [comment]
I do not think this is solely due to the bigWig file itself - it is triggered by the combination of the bigWig with a genomic location that triggers the bug. The bigWig I had trouble with originally in this issue was hanging at the Actb coordinates, on mm10, `chr5:142902205-142907664`.

**Comment by caoxiaoyi03** [comment]
While I cannot replicate the problem anymore in the current update, when I roll back to the previous commit and somehow managed to recreate the problem (see comment referred above for commit `94c968e`).

The key reason for this issue was that while in `GIVE.PineTree` children boundaries are never meant to be crossed when merging, this was not the case before the patch. 

The reason why this only happens to a few bigWig files may be that some of the files had empty regions across the genome (large chunks of `0`), which might trigger child-merging behavior to save memory usage. When it was triggered on the first child (and boundary-crossing merging happened erroneously), `currIndex` may become `-1`, which is not expected in the rest of the code.

For bigWig files with no large empty regions, the child-merging behavior may never trigger.
