### ISSUE TITLE
Visualizing my own Capture C data

### ISSUE THREAD

**Issue by Odedoron** [Zhong-Lab-UCSD/Genomic-Interactive-Visualization-Engine#99]
Very new to this.
I reached tutorial 3 where conversion from txt to BED is done. 
However I cant perform the conversion of the example file. 
I get this error:
bash: chic2give.sh: No such file or directory

I guess I need to copy the file I want to convert into the GIVE container? or Image?
I tried using ADD or COPY e.g.,
ADD E-MTAB-2323.additional.1.zip usr/local

and get
bash: ADD: command not found

What am i doing wrong?

Thanks for any help.

**Comment by frankyan** [comment]
`chic2give.sh` is a script used in tutorial 4.1. You can find the source code file [here](https://github.com/Zhong-Lab-UCSD/Genomic-Interactive-Visualization-Engine/tree/master/gallery/Demo1-captureHiC_promoter_contacts).

I don't know your data format, so I don't know whether `chic2give.sh` can correctly process your data or not. In fact, there are many different formats of Hi-C interaction data. Perhaps you need to write a script to convert your data format to [GIVE interaction format](https://github.com/Zhong-Lab-UCSD/Genomic-Interactive-Visualization-Engine/blob/master/manuals/4.3-interaction.md). That's why we don't include any official tool for format conversion.

If you want to copy file to container, you need use `docker cp` command. You can learn how to use it in the tutorial of [GIVE-Docker](https://github.com/Zhong-Lab-UCSD/Genomic-Interactive-Visualization-Engine/blob/master/tutorials/2.1-GIVE-Docker.md).

**Comment by Odedoron** [comment]
Hi Zhangming,
I am unable to complete tutorial 4.1. When I attempt the conversion to BED command:
 bash chic2give.sh TS5_CD34_promoter-promoter_significant_interactions.txt ./
I get this answer.
bash: chic2give.sh: No such file or directory

Do I need to "install" the chic2give source code? or is it already part of GIVE?
________________________________

**Comment by frankyan** [comment]
It's not include in GIVE-docker. 

It's a bash script. Its [source code file](https://github.com/Zhong-Lab-UCSD/Genomic-Interactive-Visualization-Engine/blob/master/gallery/Demo1-captureHiC_promoter_contacts/chic2give.sh) is listed in the [tutorial 4.1](https://github.com/Zhong-Lab-UCSD/Genomic-Interactive-Visualization-Engine/tree/master/gallery/Demo1-captureHiC_promoter_contacts). You need to download the source code file and run it on your linux computer.
